stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.ngram_range
    - feature_engineering.max_features
    outs:
    - models/tfidf_vectorizer.pkl
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed/train_tfidf.csv
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.num_leaves
    - model_building.min_child_samples
    - model_building.colsample_bytree
    - model_building.subsample
    - model_building.reg_alpha
    - model_building.reg_lambda
    outs:
    - models/lgbm_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/lgbm_model.pkl
    - models/tfidf_vectorizer.pkl
    - data/processed/test_tfidf.csv
    - src/model/model_evaluation.py
    outs:
    - reports/model_registry_info.json
    - reports/experiment_info.json
    - reports/metrics.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - reports/model_registry_info.json
    - src/model/register_model.py

